export {default as Chat} from "./Chat/Chat"
export {default as DuvidaCard} from "./DuvidaCard/DuvidaCard"
export {default as FileUpload} from "./FileUpload/FileUpload"
export {default as FiltroCards} from "./FiltroCards/FiltroCards"
export {default as NovaDuvida} from "./NovaDuvida/NovaDuvida"
